// 模拟一个请求回来的 allData
const imageData: ImageInter = {
    type: "IMAGE",
    isBackground: false,
    width: 300,
    height: 300,
    left: 1,
    top: 1,
    zIndex: 55,
    opacity: 1,
    transform: 0,
    rotateX: false,
    rotateY: false,
    src: "https://avatars.githubusercontent.com/u/35727398?v=4",
    originWidth: 300,
    originHeight: 300,
    relative: { left: 0, top: 0, scaleHeight: 1, scaleWidth: 1 },
    virtualKey: "20220706215255mtfq48lo0f",
};

const bgData: ImageInter = {
    type: "IMAGE",
    isBackground: true,
    background:"rgba(200,220,223,1)",
    // "backgroundImage":null
    width: 800,
    height: 800,
    left: 0,
    top: 0,
    zIndex: 1,
    opacity: 1,
    transform: 0,
    rotateX: false,
    rotateY: false,
    src: "",
    originWidth: 800,
    originHeight: 800,
    relative: { left: 0, top: 0, scaleHeight: 1, scaleWidth: 1 },
    virtualKey: "20220708234724hu3mhwjj5cq",
}
const allData: (TextInter | ImageInter)[] = [
    {
        type: "TEXT",
        content: "Text Element",
        fontSize: 68.58,
        fontFamily: "Alibaba PuHuiTi B",
        lineHeight: 2.38889,
        letterSpacing: 3.81,
        transform: 36,
        width: 500,
        height: 164,
        verticalAlign: "middle",
        textAlign: "center",
        fontWeight: "",
        fontStyle: "italic",
        color: "rgba(255,0,0,1)",
        top: 432.6587301587302,
        left: 0,
        textDecoration: "line-through",
        opacity: 0.78,
        textOrder: "horizontal",
        virtualKey: "20220614175750z7hyzapggn",
    },
    {
        type: "TEXT",
        content: "多行\n文字元素",
        fontSize: 68.58,
        fontFamily: "Alibaba PuHuiTi B",
        lineHeight: 2,
        letterSpacing: 4.81,
        transform: 0,
        width: 310,
        height: 310,
        verticalAlign: "middle",
        textAlign: "center",
        fontWeight: "",
        fontStyle: "italic",
        color: "rgba(255,0,0,1)",
        top: 180,
        left: 465,
        textDecoration: "line-through",
        opacity: 0.78,
        textOrder: "horizontal",
        virtualKey: "20220614175751z7hyzapggn",
    },
    imageData,
    bgData
];

export { allData };
